### ISSUE TITLE
Display name of plugin

### ISSUE THREAD

**Issue by awrog** [david-szabo97/grav-plugin-admin-addon-user-manager#11]
During installation of the admin-addon-user-manager plugin a faulty name is displayed
Installed a fresh copy of Grav
Add a new plugin
Choose admin-addon-user-manager
During installation a number is shown instead of the name of the plugin
![2017-07-28 08_44_19-plugins _ big picture](https://user-images.githubusercontent.com/12153667/28705752-84bbb9e2-7371-11e7-8061-139a13ba980d.png)

**Comment by david-szabo97** [comment]
@awrog 
I can't reproduce the issue.

![image](https://user-images.githubusercontent.com/2256104/28711505-1199cb72-7388-11e7-8f28-726499c9642d.png)
