### ISSUE TITLE
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)

### ISSUE THREAD

**Issue by awrog** [david-szabo97/grav-plugin-admin-addon-user-manager#12]
Fresh install Grav
Installed the admin-addon-user-manager plugin
Immediately an error is displayed:
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM)
  
![2017-07-28 08_44_42-crikey there was an error](https://user-images.githubusercontent.com/12153667/28705833-dc3a602e-7371-11e7-9fc2-e1316a1a79e2.png)

**Comment by david-szabo97** [comment]
@awrog 
I think you are running it via old PHP. I pushed a release to increase compatibility.

**Comment by awrog** [comment]
For your information, I'm using PHP version 5.6.31

**Comment by david-szabo97** [comment]
Yeah, the error popped up when I tried to lint it via 5.6. Thank you, the
new releases are now compatible with it.

**Comment by david-szabo97** [comment]
@awrog
Hopefully your issue is resolved. Please comment if it is still relevant and I'll reopen the issue.
Thank you!
