### ISSUE TITLE
Add items per page input rather than using plugin configuration

### ISSUE THREAD

**Issue by david-szabo97** [david-szabo97/grav-plugin-admin-addon-user-manager#13]

**Comment by sherpadawan** [comment]
I added this in my theme/blueprints/docs.yaml file

`
form:                                                                           
  fields:                                                                       
    tabs:                                                                       
      type: tabs                                                                
      active: 1                                                                 
      fields:                                                                   
        advanced:                                                               
          fields:                                                               
            overrides:                                                          
              fields:.                                                          
                header.access.site.login:                                       
                  type: toggle.                                                 
                  label: PLUGIN_ADMIN.SITE_ACCESS                               
                  help: PLUGIN_ADMIN.ACCESS_HELP                                
                  toggleable: true                                              
                  config-default@: system.pages.access                          
                  default: true.                                                
                  options:                                                      
                    1: PLUGIN_ADMIN.ENABLED                                     
                    0: PLUGIN_ADMIN.DISABLED                                    
                  validate:                                                     
                    type: bool                                                  
                                                                                
                header.access.groups:                                           
                  type: select                                                  
                  multiple: true                                                
                  toggleable: true                                              
                  label: PLUGIN_ADMIN.GROUPS                                    
                  help: ''                                                      
                  data-options@: '\AdminAddonUserManager\Group::groupNames'        
                  validate:                                                     
                    type: commalist   
`
