### ISSUE TITLE
How to add more permissions to each user

### ISSUE THREAD

**Issue by geogeorgejoseph** [david-szabo97/grav-plugin-admin-addon-user-manager#14]
How to add permission to user to access some pages based on the content types.

**Comment by david-szabo97** [comment]
Can you give me an example?
It seems like something that is unrelated to this plugin.

Though bulk granting and revoking of access levels are good ideas. Will open an feature request for that.

**Comment by geogeorgejoseph** [comment]
I need to add permission to some other users based on page type.



 i have 3 content/page types  -" blogs , courses , contact " and  3 users  "user1,user2,user3"

I need to add permission to above given users based on page type. for example
blogs only add/edit by user1
courses only add/edit by user2
contact only add/edit by user3

**Comment by david-szabo97** [comment]
You can use the filter to filter out the users you need then select all of them then use bulk actions.

Pushed v1.7 which adds bulk permissions actions.

**Comment by geogeorgejoseph** [comment]
But in that bulk action there is no option to select page types. Some error is occurring after the bulk option process. 

to reproduce that issue select user > click bulk option > select admin.pages as permission > click on "Add selected permissions to selected" after this process click on user-name
![admin-issues](https://user-images.githubusercontent.com/25584016/29058987-089f876c-7c31-11e7-87ce-34f3d619685a.png)

**Comment by david-szabo97** [comment]
It is not a built-in feature of Grav. You need to play with permissions to achieve what you want.
This guide shows you how to create private pages restricted to specific permissions.
https://learn.getgrav.org/cookbook/general-recipes#create-a-private-area

I just pushed v1.7.1 which changes the permissions input so now you can add custom permissions too.

About the issue, I can't reproduce it and I've never encountered something like that during testing and developing. Can you copy paste the `access` object from the account file?

Thank you
