### ISSUE TITLE
Cant add a user to a group from the group manager.

### ISSUE THREAD

**Issue by Moonlight63** [david-szabo97/grav-plugin-admin-addon-user-manager#16]
![user manager](https://user-images.githubusercontent.com/7518189/28999409-44344544-79fa-11e7-9db9-03486df7cbf5.PNG)

For some reason, is_empty() is not a function.  Probably needs to be changed to something like if(!$u['groups'].length) {}

EDIT: I was wrong. It was when removing a user from the group. And is_empty just needs to be replaced with empty. no is_

**Comment by david-szabo97** [comment]
Thank you!! (PR: https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/pull/17)
Fixed in v1.6.1 (https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/commit/58122719ed2f601b44b74a1e3322e589037628ef)
