### ISSUE TITLE
Add more permission options (or custom options)

### ISSUE THREAD

**Issue by enzimage** [david-szabo97/grav-plugin-admin-addon-user-manager#18]
Hi David
All the permissions listed (for users and for the group) are admin related.
Since I use grav to host content for paying users, I need to add for instance: **site.login**
This permission appears after I set it on the YAML file, but not before.

**Comment by enzimage** [comment]
By the way, your plugin is looking great!

**Comment by david-szabo97** [comment]
Unfortunately some permissions are not registered by plugins. `site.login` is one of the permissions which is unavailable through permission selector. Though I think this is out of the scope of the plugin, I'll add an option to add custom permissions.

Thank you!

**Comment by david-szabo97** [comment]
Please check v1.8.0, if it satifies your request then close the issue.
Thank you!

**Comment by enzimage** [comment]
I don't see any change.
I have the plugin on version v1.8.0

**Comment by david-szabo97** [comment]
You can add custom permission at the plugin`s configuration page.

**Comment by enzimage** [comment]
Awesome! That helps a lot.
Thanks David. You're really dedicated to this project.
