### ISSUE TITLE
Advanced option to edit the user's YAML file

### ISSUE THREAD

**Issue by enzimage** [david-szabo97/grav-plugin-admin-addon-user-manager#19]
When you're editing a content (eg: blog.md) file on the admin interface, you can choose "Advanced" to edit the full content of the .md file (frontmatter + markdown text). This is very useful because the admin interface doesn't have all the options for the front matter available, so you can add whatever you want there.
Something similar for the users and groups would be great for the same reason, but also to add comments inside the file.

**Comment by david-szabo97** [comment]
Good idea!
I'll look into it!

Thank you!

**Comment by david-szabo97** [comment]
Please check v1.8.0, if it satifies your request then close the issue.
Thank you!

**Comment by enzimage** [comment]
I updated the plugin but didn't see any change.

**Comment by david-szabo97** [comment]
In the user list there is a new button: expert

**Comment by enzimage** [comment]
Perfect! That does help a lot!
