### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by jakesullyneytiri** [david-szabo97/grav-plugin-admin-addon-user-manager#20]
Hi,

I have a problem when i add a user then when my friend did some changes to other plugins and cleared the cache data, thats when it kicked me out of grav and told me "Invalid Security Token" on safari browser while on chrome it told me "Invalid Login" so i noticed my account password got corrupted since i logged into my friends account and changed it and that fixed login but! Safari is still throwing "Invalid Security Token" i have flushed cookies, cache and such bit just throws same thing what so ever.

I hope you can fix this asap

/Thanks

**Comment by david-szabo97** [comment]
Hi there,

The "creating a new user" part is not related to the plugin. The plugin just redirects you to the built-in page.

https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/blob/master/templates/user-manager.html.twig#L132

**Comment by david-szabo97** [comment]
Closed due to inactivity, please reopen it if it is still relevant.
