### ISSUE TITLE
granular control

### ISSUE THREAD

**Issue by pixelliquid** [david-szabo97/grav-plugin-admin-addon-user-manager#24]
When activating the plugin for a user, this user gets too much control. This user can delete a super admin, which is not wanted behavior.

**Comment by david-szabo97** [comment]
Do you have any idea how we could overcome this?
Any good system that we could implement to handle such cases.

I was thinking about giving a 'power' or 'level' or call it whatever to each group. And a user can only edit users with lower power. It's a naive solution but better than nothing.

We need to come up a good system which can handle most of the use cases. If you have any idea then share it here please.

**Comment by finanalyst** [comment]
I had a similar problem, and I've just added a new issue.

The problem is that using this user manager plugin, new users are not given *site login access*. That means that only users (created by this plugin) who have *supervisor login access* can actually login. I agree with the initial poster that it is undesirable to give **all** users *supervisor login access*.

The work-around is to use `expert` mode for the user and to add the following lines to the section `access`:
```
access: # this line already is in the user file
  site:
    login: 'true'
```

**Comment by adamschmid** [comment]
Agreed. This plugin is pointless for administrators wishing to give users some control of managing content of a website without allowing them to either:

1. Assign themselves new permissions above the level they already have or 2. delete/modify users with permissions above their level (i.e. _ACTUAL_ admins who would be kicked out of the system by a subordinate user).

There needs to be a check in place that looks to see if a user has permission to overwrite admin level permissions.

**Comment by david-szabo97** [comment]
@adamschmid Yes, that's not the purpose of the plugin anyway. And maybe that's not even possible without modifying Grav core.

**Comment by sebastianbaumann** [comment]
So any news on this?
I don't want users, who have access to ` admin-addon-user-manager: users: true` to be able to edit or even delete the admin…

**Comment by adamschmid** [comment]
@david-szabo97 Would you consider making this plug-in more useful to administrators wishing to grant certain access levels to other Grav admin users for updating content, etc? Use case is something along the lines of how Wordpress handles users. There really isn't anything else from what I've seen that comes close to managing users in Grav. The plugin description itself then seems misleading if the purpose isn't to control a user's access. 

> _"A simple admin panel extension which adds the option to manage users and groups."_

All this does is allow a user access to the admin section where they, themselves would technically be an admin despite assigning a specific group of roles/functions can easily be overridden by said user. Was this your intention?

**Comment by david-szabo97** [comment]
@adamschmid We are kinda limited by how Grav Admin and Grav Core works. The purpose of this plugin is to edit your users and groups file via interface.

**Comment by david-szabo97** [comment]
@adamschmid Why can't you use the built-in permissions to prevent full admin access for editors? You can do all the permission changes using the interface provided by this plugin.

**Comment by Heraes-git** [comment]
@david-szabo97 Except that there seems to be a bug, forcing us to give superadmin rights, as I mention it here : https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/issues/56

**Comment by david-szabo97** [comment]
Grav v1.7.0 has a built-in interface for managing users and groups. 🎉 I'm discontinuing the plugin. Thanks for using my plugin for the time being! 🙇
