### ISSUE TITLE
Change avatar problem

### ISSUE THREAD

**Issue by pr0ma** [david-szabo97/grav-plugin-admin-addon-user-manager#25]
After update Admin Panel plugin Admin Addon User Manager not work normal.
Try change avatar - result error "Data type 'user-manager/test' doesn't exist!"
![2017-12-08 10 57 48](https://user-images.githubusercontent.com/34234320/33873933-93df1f98-df25-11e7-916b-84ee67812ecb.png)

**Comment by SethG911** [comment]
Getting the same issue here.

**Comment by david-szabo97** [comment]
Thanks for reporting, I will take care of it this week.

**Comment by david-szabo97** [comment]
Fixed in v2.0.0

**Comment by iqvision** [comment]
Cannot modify avatar.

**Comment by david-szabo97** [comment]
@iqvision 
Could you give more information please? Maybe a screenshot or video recording about the issue? Console errors? Server log? Anything that would help me?
