### ISSUE TITLE
Memory leak when using non-ascii character (?) to create group

### ISSUE THREAD

**Issue by Marcool04** [david-szabo97/grav-plugin-admin-addon-user-manager#26]
Hi there. This is a cross-post after a short discussion on the grav core github issue tracker. It seems the issue may have been related to something in grav core but apparently the plugin is now the likely culprit.

First a bit of context:
````
[root@alarmpi ~]$ uname -a
Linux alarmpi 4.9.65-1-ARCH #1 SMP Fri Nov 24 17:54:03 UTC 2017 armv7l GNU/Linux
[root@alarmpi ~]$ pacman -Qi apache | grep Version
Version         : 2.4.29-1
[root@alarmpi ~]$ php --version
PHP 7.1.12 (cli) (built: Nov 22 2017 17:42:00) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.12, Copyright (c) 1999-2017, by Zend Technologies
````
I was trying to create a new group in a fresh Grav installation, using the name "Utilisateur enregistré". First the page just went blank, and I noticed the following error in my server log:

````
Got error 'PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 12288 bytes) in /usr/share/webapps/grav/vendor/rockettheme/toolbox/File/src/File.php on line 254\nPHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /usr/share/webapps/grav/vendor/filp/whoops/src/Whoops/Util/Misc.php on line 50\n', referer: https://abbasp.archmacbook.tk/grav/admin/group-manager/Utilisateurs%20enregistr%C3%A9s
````
I then increased the memory limit to 512M (from default 128M) just to see if that was the issue, but monitoring the memory usage showed a perfect ramp all the way up to full usage, see [screenshot](https://framapic.org/gallery#iOYhJvJAnXei/x2aC1K92vi9p.png). In the end the php timeout was reached:
````
Got error 'PHP message: PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /usr/share/webapps/grav/vendor/rockettheme/toolbox/File/src/File.php on line 254\n', referer: https://abbasp.archmacbook.tk/grav/admin/group-manager
````
Changing the timeout to 300 seconds then crashed the server for a long time, until linux OOM handler could scavenge it somehow I suppose.
On the other hand, changed the group name to "Users" it works perfectly, so my intuition is this could be an issue with the character encoding.
Let me know if more info is needed, I'm happy to help track this down.

**Comment by david-szabo97** [comment]
Thank you for reporting. It is fixed now.

**Comment by Marcool04** [comment]
Wow that was fast :) I'll give it a try later on and let you know how it goes.

**Comment by Marcool04** [comment]
Awesome, confirmed working after update to v1.9.1
Thanks a bunch for the lightning fast reaction and solution.
