### ISSUE TITLE
Admin Links Stop Working

### ISSUE THREAD

**Issue by oldmanumby** [david-szabo97/grav-plugin-admin-addon-user-manager#27]
Greetings, I really love this plugin. However, when viewing a user profile, all buttons and links stop working. By that I mean, you cannot get out of the page. Back or Save doesn't work, and none of the links in the admin menu to the left work either. The only way to get off the page is to change the URL manually in the address bar.

I did manage to create a new user, but it was after that the issued showed itself.

This is a brand new site, I am running the latest BETA of GRAV + Gantry and everything is updated.

Suggestions?

Umby

**Comment by david-szabo97** [comment]
Hi Umby!

Thank you for reporting the issue! Once I had this issue but I thought it disappeared. Now I was able to reproduce it and fix it! (v2.0.1) (3789b2ba320864c76f5dcc9511855ebb7f096908)

David
