### ISSUE TITLE
wrong routing - user delete button

### ISSUE THREAD

**Issue by soeren-mueller** [david-szabo97/grav-plugin-admin-addon-user-manager#28]
Hi,
nice Plugin! =)
After deleting an user, I get a 404 page at "mysite.demo/user-manager". The correct url shoud be "mysite.demo/admin/user-manager"
How long will it take to fix it?
Thanks!

**Comment by david-szabo97** [comment]
Thank you for reporting the issue!

Fixed via https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/commit/1bd9704d5f13025a1254a989387825142df5019c

(Messed up commit message issue linking)
