### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by 07pepa** [david-szabo97/grav-plugin-admin-addon-user-manager#29]
it is not posible to  change language anyhow !

**Comment by david-szabo97** [comment]
The language is determined by Grav Admin not by the plugin itself.
Please give me more details.

**Comment by 07pepa** [comment]
i added cs.yaml  to languages to your plugin and czech language is selected in grav admin

**Comment by david-szabo97** [comment]
Please take screenshot or something so I can see where is the issue. It might be a string which is not setup to be translated

**Comment by 07pepa** [comment]
it is basicly everything  that is not translated
http://prntscr.com/ibvaqg
http://prntscr.com/ibvbtq
cs.yaml in same folder as yours en.yaml look like this

PLUGIN_ADMIN_ADDON_USER_MANAGER:
  GROUP: skupina
  READABLE_NAME: Čitelné jmeno
  ICON: Ikona
  ADD_GROUP: Přidej skupinu
  USERS: Uživatelé
  HELP: Pomoc
  BULK_DELETE_USER: Smaž vybrané uživatele
  BULK_DELETE: Smaž
  BULK_USER_GROUP: Hromadné akce s vybranou skupinou
  BULK_ADD_GROUP: Přidej vybrané uživatele do vybrané skupiny
  BULK_REMOVE_GROUP: Odeber vybrané uživatele z skupiny
  BULK_DELETE_GROUP: Smaž vybrané skupiny
  BULK_ADD_PERMISSIONS: Přidej vybrané práva vybraným uživatelum
  BULK_REMOVE_PERMISSIONS: Odeber vybraná prava vybraným uživatelům
  LOGIN_AS: Přihlasit jako
  USER_CONFIRM_DELETE: Opravdu chcete smazat tohoto uživatele?

ps: you have my premision integrate it into this plugin

**Comment by david-szabo97** [comment]
Thanks!

I will make sure to include all the untranslated strings in the language file in the next release.

**Comment by david-szabo97** [comment]
@07pepa 
Hey! Just pushed v2.0.3 which adds missing translation strings.
Hopefully you won't mind in adding the missing ones to your czech translation so I can release the plugin with czech language support 😄

**Comment by 07pepa** [comment]
there are your  string ... be careful i did not  not know if copiing it here will preserve CR LF on end of rows and null on end of  file 😜

PLUGIN_ADMIN_ADDON_USER_MANAGER:
  USER_MANAGER: Správce uživatelů
  GROUP_MANAGER: Správce skupin
  MANAGE_USERS: Zpráva uživatelů
  MANAGE_GROUPS: Zpráva skupin
  FILTER_ERROR: Chyba filtru
  FILTER_USERS: Filtruj uživatele
  FILTER_GROUPS: Filtruj skupiny
  NO_RESULTS: Žádné shody
  EXPERT: Expert
  PAGINATION_SUMMARY: Zobrazeno %d - %d z %d
  BULK_ACTION:  Hromadné akce
  ACTIONS: Akce
  CUSTOM_PERMISSIONS: Specifická opravnění
  CUSTOM_PERMISSIONS_PLACEHOLDER: "opravnění (např. 'site.login')"
  USERS_PER_PAGE: Uživatelů na stránku
  DEFAULT_LIST_STYLE: Výchozí styl listu
  GRID: Mřížka
  LIST: Stránka
  GROUP: Skupina
  READABLE_NAME: Zobrazené jméno
  ICON: Ikona
  ADD_GROUP: Přidat skupinu
  USERS: Uživatelé
  HELP: Pomoc
  BULK_DELETE_USER: Delete selected users
  BULK_DELETE: Delete
  BULK_USER_GROUP: Bulk user actions related to groups
  BULK_ADD_GROUP: Add selected users to selected groups
  BULK_REMOVE_GROUP: Odeber vybrané uživatele
  BULK_DELETE_GROUP: Odeber vybrané skupiny
  BULK_ADD_PERMISSIONS: Přidej vybraná opravnění vybraným 
  BULK_REMOVE_PERMISSIONS: Odeber vybraná opravnění vybraným uživatelům
  LOGIN_AS: Přihlaš se jako
  USER_CONFIRM_DELETE: Opravdu chcete smazat tohoto uživatele?

**Comment by david-szabo97** [comment]
Thank you, I'll add it next week!

**Comment by david-szabo97** [comment]
Fixed/Added in v2.1.0
