### ISSUE TITLE
Authorization to remove a theme

### ISSUE THREAD

**Issue by unmick** [david-szabo97/grav-plugin-admin-addon-user-manager#30]
Hello, 

Do you know if there is a way to authorize user to setup a theme but not to remove it ?
There is the admin.theme but it gives an important right for an user...

Thanks for your help !

**Comment by david-szabo97** [comment]
Hi there! I don't think there is a separate permission to handle those
cases. You may open an issue at grav admin plugin to add that. But I look
into it, maybe we can habdle that via plugin.
