### ISSUE TITLE
Exception raised when using the expert mode.

### ISSUE THREAD

**Issue by hemedb** [david-szabo97/grav-plugin-admin-addon-user-manager#33]
Hello there,

Got an error "Call to a member function post() on null" at  …/user/plugins/form/form.php:184 when clicking the "save" button modifying a user properties in expert mode.

Steps to reproduce:
- create a user via the users admin plug-in
- back to the list of user
- click expert for the user just created
- change something (I changed the language)
- click save

Environment:
- Linux Mint Debian Edition "Betsy" (Debian 8 Jessie)
- Apache 2.2.2
- PHP 7.2.2
- Grav v1.4.0-rc.2 - Admin v1.7.0-rc.3
- Admin Addon User Manager v2.0.3
  
Post data :
raw | """ state: enabled\r\n email: xxxxxx@xxxxx.com\r\n fullname: 'a test user'\r\n language: fr\r\n twofa_enabled: false\r\n twofa_secret: UK7MCEYWZ6LVRKYJJ3UMNTI7E77AHYGS\r\n access:\r\n   admin: {  }\r\n   admin-addon-user-manager: {  }\r\n hashed_password: $2y$10$WEV.rAA.ulF3h/w9Ag2l0eXFy.yUrbkQsOM8hAdnHW5ogc.z.VPzq\r\n """
-- | --
form-nonce | "824ed52fa2613d207cc833986bf626b0"

I've tried various simple things like clearing the cache, changing the data, etc..., but the problem still occurs.

Thanks for the plug-in, very useful, makes admin life much easier...

Regards,

Michel.

**Comment by filisko** [comment]
Happens the same to me :wink:

**Comment by david-szabo97** [comment]
This is an issue with the Form v2.11.4 plugin. Works fine with older versions and this issue seems to be fixed in the new version which should be released soon.

**Comment by hemedb** [comment]
Ok, thanks. Wait and see then...

**Comment by hemedb** [comment]
Yes, solved with Form 2.11.5.
