### ISSUE TITLE
Minimum required permissions to add user and groups

### ISSUE THREAD

**Issue by AxelRHD** [david-szabo97/grav-plugin-admin-addon-user-manager#34]
Great plugin. But I have problems to set the right permissions for our head of department, so that he can add/edit users and groups but nothing else (no super user). I gave him permission for the plugin (and admin.users) and tried with his account to create a new user. But I can't save the profile (error action 'save').
What am I missing?

**Comment by david-szabo97** [comment]
Fixed in v2.1.0
