### ISSUE TITLE
/admin/group-manager 404 not found

### ISSUE THREAD

**Issue by newmedicine** [david-szabo97/grav-plugin-admin-addon-user-manager#35]
Internal "grav" 404 that is. 
Grav v1.4.1 - Admin v1.7.1 - addon-user-manager 2.1.0

Also, when I try to edit a user in /admin/user-manager, I get exception `Whoops \ Exception \ ErrorException (E_ERROR)
Maximum function nesting level of '100' reached, aborting!` in  `/home/bacfc/public_html/g/vendor/twig/twig/lib/Twig/Compiler.php` lines:
```
    public function raw($string)
    {
        $this->source .= $string;
 
        return $this;
    }
```
If you need any more debug info please say
Nick

**Comment by david-szabo97** [comment]
Hi Nick!

I can't reproduce this.

Do you have any other information available which may help?

**Comment by david-szabo97** [comment]
@newmedicine 
Bump, is this still relevant?

**Comment by david-szabo97** [comment]
Closed due to inactivity.
