### ISSUE TITLE
new user not allocated site login

### ISSUE THREAD

**Issue by finanalyst** [david-szabo97/grav-plugin-admin-addon-user-manager#36]
I have a site in which some pages, but **not all** pages, have the following in the page header
```
access:
  site.login: true
```
I create a new user, eg., `candy`, using `grav-plugin-admin-addon-user-manager`. BUT in `candy.yaml` there is no entry
```
access:
  site:
    login: 'true'
```
There are only entries for supervisor mode. This means that `candy` does not have *site login access*.

Consequently, the new user (`candy`) cannot login to the pages that require *site login access*

My suggestion is that a new user is automatically given *site login access*, because if someone wants to create a situation where a user does **not** have *site login access*, the administrator can use `expert` mode to delete the relevant lines in the <user>.yaml.

Also the same for groups. There is no way for a group to be edited (without the `expert` mode) to allocate to members of the group *site login access*.

It took me a long time to work out why the login was being rejected. My assumption was that any registered user automatically was given *site login access*. This is not true.

I suspect that other people have made the same assumption (I've added comments to one issue accordingly).

It seems to me that this is on the level of a *bug* rather than an enhancement or extra feature because it concerns the lowermost security setting.

**Comment by david-szabo97** [comment]
Hi Richard!

Actually this is not an issue with the plugin itself. The Admin plugin doesn't expose the site.login permission. That's why it doesn't show up in the list.

You can overcome this by adding it as a custom permission via this plugin.

Here is an example:

![image](https://user-images.githubusercontent.com/2256104/37802620-89c3e340-2e2b-11e8-8156-92094fc78218.png)


I will be honest. I think this causes user experience issues (like yours), so I release a hotfix which makes sure this specific permission is automatically added into the list.

Thank you!

**Comment by david-szabo97** [comment]
It's released: v2.1.1

**Comment by finanalyst** [comment]
Hi David!
We met on perl6 topics, Bailador??
I keep thinking it would be nice to do a sort of Perl6 Grav :)

Richard

**Comment by david-szabo97** [comment]
@finanalyst 
Hi Richard!

I don't think we have ever met, well not on perl6 topics that's for sure :) I have never worked with Perl :)

Did v2.1.1 fixed your issue? If it did, please close the issue :)

**Comment by david-szabo97** [comment]
Closed due to inactivity, reopen if neccessary

**Comment by finanalyst** [comment]
Not reopening. Just adding info. Sorry for the delay - other things to do.
a) The change you made helped. On my site the site.login permission was right at the very end of the list of permissions. Is there a way to put it first?
b) I realised I confused you with Gabor Szabo, who lives in Israel. My bad. Sorry.

**Comment by david-szabo97** [comment]
I am not sure if we can do that. But I will look into it.

**Comment by david-szabo97** [comment]
@finanalyst Moved the permission to the front.
