### ISSUE TITLE
Issue installing with PHP Version

### ISSUE THREAD

**Issue by camigolden** [david-szabo97/grav-plugin-admin-addon-user-manager#4]
Hi! 
I'm having the following issue when i install the plugin in a server with php 5.5.38 it gives me an error in line 13 of the file admin-addon-user-manager.php
the line it's the following  const CONFIG_KEY = 'plugins.' . self::SLUG;
and i don't know how to fix it when i install it in my local server it doesn't have a problem the version there it's much higher 7.11 but is there a way to fix it for the 5.5.38 version??
thanks!

**Comment by Wojtziech** [comment]
[Expression at definition of constant requires PHP 5.6](https://wiki.php.net/rfc/const_scalar_exprs), while [minimum version for Grav is 5.5.9](https://learn.getgrav.org/basics/requirements).

After changing this line to:
`const CONFIG_KEY = 'plugins.admin-addon-user-manager';`
everything seems to work properly.

**Comment by camigolden** [comment]
Thank you! i will try it 👍
