### ISSUE TITLE
Identifier "admin" is not defined.

### ISSUE THREAD

**Issue by finanalyst** [david-szabo97/grav-plugin-admin-addon-user-manager#40]
After the update to user-manager 2.1.4 , I am getting the subject error. 

I deleted `grav-plugin-admin-addon-user-manager` and the error disappeared.

I reinstalled plugin and the error reappeared.

See screenshot for the error message.

![screenshot from 2018-04-09 14-31-50](https://user-images.githubusercontent.com/363676/38482924-bc7148ba-3c03-11e8-95dd-8445f308c955.png)

**Comment by david-szabo97** [comment]
Fixed in v2.1.5
Sorry about this. I think that's what you get for trying to quickly to do something.

I wonder why this event is even called on the front-end though.
