### ISSUE TITLE
Group config bug?

### ISSUE THREAD

**Issue by finanalyst** [david-szabo97/grav-plugin-admin-addon-user-manager#44]
I just created a new first group. The groups.yaml file in `user/config` has permission 644, it should be 664. The latter is the standard for all Grav files. The reason is that I tend to set myself as the owner of Grav files, and have the unix group set to www-data so that the Appache/NGINX software can also alter it.

The setup where I noticed this is a Synology NAS. It is a linux based, but proprietary, OS. It may be an OS issue that the file permission has to be set on creation.  

I am filing another issue regarding the setting of user passwords. I am not sure if these problems are related.

**Comment by david-szabo97** [comment]
@finanalyst I use the Grav internals to do the file handling, so this I am pretty sure this is out of our scope. Are you sure 664 is the default in Grav? I found a lot of 644 references in the source code but not 664.

**Comment by david-szabo97** [comment]
Closed due to inactivity
