### ISSUE TITLE
Setting new passwords to existing users in Admin

### ISSUE THREAD

**Issue by finanalyst** [david-szabo97/grav-plugin-admin-addon-user-manager#45]
I am having problems when I try to reset the password of a user in the User Admin section.
I set a new user, set the password in the Admin section, but the login does not work. I think that the password is incorrect, so I try to reset the password. But still I cannot log in.

I have tried wiping browser history, clearing all the cache, and some other things, but I cannot get a login to work.

I am not sure why this is happening. Would it be possible for you to specify the exact steps needed to ensure that a new login password reset in the UserAdmin plugin is recognised in the site? 

I have encountered this problem with a server running Ubuntu 17.10 and Synology OS.

**Comment by motherdomains** [comment]
Same issue, running Ubuntu 16.04. It doesn't appear that the password is saving. Group permissions aren't saving either - in the name of the group/s I'm in, it says my username instead.

**Comment by bobbwal** [comment]
Similar issue here. If I register a user via the login plugin then make changes to the account via the user manager profile page it's seems the password is changed and the user can no longer login.

**Comment by bobbwal** [comment]
Yep, can confirm every time the profile is saved the password is changed.

**Comment by david-szabo97** [comment]
Cannot reproduce. Closed due to inactivity.
