### ISSUE TITLE
Setting group special permission in GUI

### ISSUE THREAD

**Issue by finanalyst** [david-szabo97/grav-plugin-admin-addon-user-manager#46]
I want to use the option of having a group specify a login permission. So anyone in the group can access a page using existing Login plugin potential.

However, there does not seem to be the option to have 'expert' access to the group's permissions. Compare with 'expert' access to a user's permissions. 

For the group, eg. 'operations', I need to be able to set
```
access:
    site:
        special: true
```
So on a protected page that should be accessible to users in the 'operations' group, I have
```
access:
    site:
       special: true
```
This means that I do not need to set the access permission for each user.

I am thinking that the problems raised in another issue could be solved by an appropriate combination of access permissions on a page.

**Comment by david-szabo97** [comment]
@finanalyst That's right, we don't have expert edit for groups but I am pretty sure we don't need it. You can add custom permission in the plugin's config. (Plugins -> Admin Addon User Manager -> Custom Permissions) Add "site.special" there and you are good.

**Comment by david-szabo97** [comment]
Closed due to inactivity.
