### ISSUE TITLE
Kind request to change Expert to Edit

### ISSUE THREAD

**Issue by bleutzinn** [david-szabo97/grav-plugin-admin-addon-user-manager#49]
The purpose of the 'Expert' button is to edit the user configuration. So why not have that button show 'Edit' instead of 'Expert'?

**Comment by david-szabo97** [comment]
@bleutzinn I don't think this would be a good change. You can edit the user by clicking on the username - that's the friendly way. Then we have an expert mode when you click on the expert button.

**Comment by bleutzinn** [comment]
Ah, I see. Sorry, I've never clicked on the user name. I suppose my attention was directly drawn towards the "Actions" column.
Thanks.
