### ISSUE TITLE
List users in list style

### ISSUE THREAD

**Issue by enzimage** [david-szabo97/grav-plugin-admin-addon-user-manager#5]
I've created a Grav website with over 500 users. An option to see a list of users with their email/names/usernames would be easier to manage.
Still, a very useful plugin!

**Comment by david-szabo97** [comment]
Woah, that's definitely a lot of users! I will make some changes to make
sure it is usable with lots of user too. Like pagination, search feature
and list view.

**Comment by enzimage** [comment]
Great David, thanks for responding so quickly.
Indeed we have a lot of users accessing our content. We had another website with more than 4000 users. Both were WordPress websites.
The largest one we terminated and this (which is more important to us) we migrated to Grav.

**Comment by david-szabo97** [comment]
Just pushed v1.2.0

I have added pagination and list style. Please give it a check and let me know if you find any bugs or you have any ideas to improve it!

Pagination is still work in progress, I will make it a bit more user friendly, like next ,previous and show less pages.

I am not sure about the performance, I will definitely look into caching.

Thank you :smile:

**Comment by enzimage** [comment]
Hi David, Sorry for the delay.
I installed the update and immediately got this:
`Server Error
Sorry, something went terribly wrong!
E_WARNING - array_slice() expects parameter 1 to be array, null given
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.`

**Comment by david-szabo97** [comment]
Oops, sorry about that :smile:

Pushed v1.3.2 to fix it

**Comment by enzimage** [comment]
Looking good!
I already found out that grav didn't recognize some of the emails on the accounts when I imported them, so I need to do some work on that. Wouldn't have figured it out without your plugin.

![image](https://user-images.githubusercontent.com/30270303/28413412-af8d0444-6d47-11e7-821f-1d2881d50c05.png)

**Comment by david-szabo97** [comment]
Great!

I'll close this issue, I have opened a few other feature issues. Give 'em a check if you have some free time and let me know if you have any ideas to improve the plugin!

Thank you!
