### ISSUE TITLE
call_user_func_array error

### ISSUE THREAD

**Issue by chhinsras** [david-szabo97/grav-plugin-admin-addon-user-manager#53]
I just new to grav, it looks interesting.

When, I install everything working fine. Then, I started to some plugins.

The error call_user_func_array() occured.

Please help me.

![err](https://user-images.githubusercontent.com/31751665/52907334-5a1d6280-3292-11e9-9c37-e6fddda351e9.png)

**Comment by david-szabo97** [comment]
Hi @chhinsras,
I closed this issue. If this is still relevant please reopen it. Thanks!
