### ISSUE TITLE
Add option to disable or activate user not in expert mode

### ISSUE THREAD

**Issue by dimitrilongo** [david-szabo97/grav-plugin-admin-addon-user-manager#54]
in `myuser.yaml` i had `state: disabled` by default, a choice  because i’d like that admin enable them one by one. Of course he can enabled them by editing the yaml in expert mode, i think it would be great to have a toggle button to enable  or disable them

**Comment by david-szabo97** [comment]
Added in v2.2.0

**Comment by dimitrilongo** [comment]
@david-szabo97 thanks for this update
