### ISSUE TITLE
Impossible to attribute a group to a user without being superadmin

### ISSUE THREAD

**Issue by Heraes-git** [david-szabo97/grav-plugin-admin-addon-user-manager#56]
After 2 hours of testing in every direction, I'm now sure that : 

- It is impossible to set a user the power to define other user's level, without being himself a superadmin.
- So the users management is reserved to a superadmin, wich can be a problem if we want to give the users management to the owner of the website, without giving him super-powers.

What I would like is to give the client basic configuration, page editing, and users management, but without advanced functions like "Tools", "Plugins", or the "System" tab of "Configuration".

So the level map would be : 
- Members : site login access.
- Editors : site + admin access, with pages edition only.
- Administrators : site + admin access, with pages edition + **users management** + _light_ config.
- Super-admin (useful for the  webmaster) : site + admin + **super** (full access).

**Unfortunately, it seems that your plugin necessitate to check the "Super" option**, in order to see the field corresponding to the Groups, in the users' management panel.

So, even if these switch are ON : 

![2019-03-22_23h26m27s_chrome](https://user-images.githubusercontent.com/22033256/54860087-417eed00-4d15-11e9-88e0-2267c000f05b.jpg)

If the SUPER switch is OFF  :

![2019-03-23_02h46m12s_chrome](https://user-images.githubusercontent.com/22033256/54860125-d5e94f80-4d15-11e9-9354-f90e62e6b67b.jpg)

The users' manager panel **won't**  show any Group permission as you can see below (where it doesn't appear) : 

![2019-03-22_23h25m36s_chrome](https://user-images.githubusercontent.com/22033256/54860115-a20e2a00-4d15-11e9-9243-85f269f6d942.jpg)

**Comment by Heraes-git** [comment]
I forgot one thing : of course, setting "SUPER" to _ON_ while setting all **sub-rigths to _OFF_** doesn't work !
It could have been a logical approach, but unfortunately, powering _ON_ the "SUPER" switch forces all sub-rules to be implied in the role. 

It's not the same for the "ADMIN" or "CONFIG" switch : we can set it to _ON_ while selecting one of its sub-rule to _OFF_, and the peculiar rule will be deactivated as expected.

Also, applying **two groups** to a user, one having the SUPER switch _ON_, and the other having it to _OFF_, doesn't work : the more restrictive (OFF) wins over the other.

**Comment by david-szabo97** [comment]
@Romarain The plugin is not controlling the permissions. It's controlled by Grav/Grav Admin.

**Comment by Heraes-git** [comment]
@david-szabo97 There is two logical problems here : 
1. The SUPERUSER seems to have a strange behavior, with no care of sub-rules.
2. And your plugin seems to be unable to show some of its own fields (like Groups) in a user's page.

Can you confirm me that 1 is not due to your plugin, and that 2 is because there an absolute necessity to user SUPERUSER permission in order for your plugin to display users' options that it is supposed to bring and manage ?

Don't be offended, but I suspect a bad design in your plugin. What things is specifically avoiding your plugin to read user's account file, and to edit it, with just admin rights ? (especially the `groups:` YAML option) ? What do you need ?

And did you contacted the Grav staff in order to solve this problem ?

**Comment by david-szabo97** [comment]
This plugin doesn't extend the permission system of Grav. It just exposes an interface to edit/create/delete users and groups. I am not sure how we could tackle the granularity/power level yet.
