### ISSUE TITLE
Can not remove group from user at /user-manager/

### ISSUE THREAD

**Issue by Rotzbua** [david-szabo97/grav-plugin-admin-addon-user-manager#57]
## Environment

Admin Addon User Manager v2.1.6
Admin Panel v1.8.20 
Grav 1.5.10
php 7.1

## Reproduce

1. add a user to a group by /admin/user-manager/
1. save
1. remove group
1. save
1. group is still assigned

## Workaround

1. create a dummy group without any permission
1. remove old group
1. replace by dummy group
1. save

## Solution at other place

1. use /admin/group-manager/, at bottom and remove user
1. save

**Comment by david-szabo97** [comment]
Can't reproduce anymore so let's take it as fixed. Reopen if it is still relevant.
