### ISSUE TITLE
Groups management

### ISSUE THREAD

**Issue by david-szabo97** [david-szabo97/grav-plugin-admin-addon-user-manager#6]
- [x] List groups
- [x] Add groups
- [x] Remove groups
- [x] Add users to groups
- [x] Remove users from groups
- [x] List users in groups

**Comment by enzimage** [comment]
This is useful.
I think this would be useful if it worked together with filters.
Ex: filter everyone who is not a admin, add everyone to the "free access" group.

**Comment by david-szabo97** [comment]
Implemented in v1.5.0

@enzimage 
Such feature will be added in the next version. Follow up issue: #10 (Bulk Actions)
