### ISSUE TITLE
Error adding group 

### ISSUE THREAD

**Issue by lauroguedes** [david-szabo97/grav-plugin-admin-addon-user-manager#60]
When trying to add a group is giving the following error: 

`in_array() expects parameter 2 to be array, string given`

![Capturar](https://user-images.githubusercontent.com/3677780/61248758-1ee06c00-a72a-11e9-88e6-4b302f74adb2.PNG)

**Comment by david-szabo97** [comment]
Can't reproduce. If this issue is still going on for you, please reopen and tell me more details
