### ISSUE TITLE
send an email to the creation of a user

### ISSUE THREAD

**Issue by RomainLWiz** [david-szabo97/grav-plugin-admin-addon-user-manager#62]
Being able to send an email with a link or a personalized message would be really practical. Or an alternative idea ?

**Comment by david-szabo97** [comment]
I am not sure. What use case do you have in mind?

**Comment by MakaryGo** [comment]
I think that [login] already provides this function?
Or do you have something else in mind?

[login]: https://github.com/getgrav/grav-plugin-login/blob/develop/README.md#send-a-welcome-email

**Comment by RomainLWiz** [comment]
What I am looking for and the creation of a user we enter his email and I would like the plugin to send him an email directly.

**Comment by david-szabo97** [comment]
You can do it by using the "Send welcome email" option as @MakaryGo mentioned.
