### ISSUE TITLE
Grav Report indicates YAML linting error

### ISSUE THREAD

**Issue by rafvandevreugde** [david-szabo97/grav-plugin-admin-addon-user-manager#63]
Hello,

After updating to the latest version (2.2.0), the Grav Reporting gives an error:

`
/user/plugins/admin-addon-user-manager/blueprints/user/aaum-account.yaml 
`

`
The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 10 (near "@ordering: content").
`

Regards,

    Raf

**Comment by david-szabo97** [comment]
Thanks for reporting. Fixed in v2.2.1
