### ISSUE TITLE
Plugin not working with last update

### ISSUE THREAD

**Issue by zouloux** [david-szabo97/grav-plugin-admin-addon-user-manager#64]
Hi and thanks for this useful plugin :)
It seems that after updating to last plugins I got an error when trying to get "User Manager" tab in admin.
`$page` is null at line 110. Patched with this : 
```
$page = $this->grav['admin']->page(false); // inverted $route boolean
```
I don't know where the bug really comes from but if it can helps anybody.
Thanks !

**Comment by ackinty** [comment]
Same symptoms here with 
Grav v1.6.23 - Admin v1.9.13 - Admin Addon User Manager v2.2.1

Patch from zouloux is working. Thx @zouloux :)

**Comment by david-szabo97** [comment]
@ackinty Can you tell me how to reproduce this?
Fresh install of v1.6.23 works fine. Maybe a plugin conflict?

**Comment by zouloux** [comment]
Hi, will re-try soon and keep you posted.

**Comment by zouloux** [comment]
It's working fine now, thanks !

**Comment by zouloux** [comment]
Got back the error after saving a user. `->page(false);` still patching it.

**Comment by david-szabo97** [comment]
@zouloux Please post your plugin list, thanks!

**Comment by zouloux** [comment]
Hi @david-szabo97, I'll try to post a max of info a soon as I got some time. I'll try to setup from a clean-install also. I keep you posted, thanks.

**Comment by david-szabo97** [comment]
Closed due to inactivity.
