### ISSUE TITLE
Usage of User::load() is deprecated since Grav 1.6

### ISSUE THREAD

**Issue by renepapenfuss** [david-szabo97/grav-plugin-admin-addon-user-manager#66]
I get this message in Deprecation tab in the debugger bar:

`Grav\Common\User\User::load() is deprecated since Grav 1.6, use $grav['accounts']->load() instead`

**Comment by david-szabo97** [comment]
Fixed in https://github.com/david-szabo97/grav-plugin-admin-addon-user-manager/commit/cfcdc60b7b3d3e04b138a843b7a8408b20e0a3d8
