### ISSUE TITLE
Can't view User Manager Page when changing the Administrator Path

### ISSUE THREAD

**Issue by localnetwork** [david-szabo97/grav-plugin-admin-addon-user-manager#67]
Seeing this when changing admin path

![screenshot-prestigelabelsco s14-host com-2020 03 30-16_08_59](https://user-images.githubusercontent.com/15809239/77889791-03f65d80-72a1-11ea-9dc4-8b66da0ef8c5.png)

instead of this:

![screenshot-prestigelabelsco s14-host com-2020 03 30-16_09_27](https://user-images.githubusercontent.com/15809239/77889828-12dd1000-72a1-11ea-8f31-80144d66468d.png)

**Comment by david-szabo97** [comment]
@localnetwork Just tested this and couldn't reproduce. I changed my path several times and no issues.
Do you have any other plugins? Can you test on a fresh install?

**Comment by david-szabo97** [comment]
Closed due to inactivity.
