### ISSUE TITLE
Simple search fallback  

### ISSUE THREAD

**Issue by christopherhemme** [david-szabo97/grav-plugin-admin-addon-user-manager#69]
The current filter functionality is super flexible but for me the most common usecase is to search for a user by a part of the username. therefor it would be great to have a "simple search" as a fallback. So if I enter 'John' in the search field the query will fail and it will filter instead for `user.username matches '/[John]/'` and will list me John Doe.

**Comment by david-szabo97** [comment]
Released in v2.5.0

Thanks!
