### ISSUE TITLE
Filter and Search

### ISSUE THREAD

**Issue by david-szabo97** [david-szabo97/grav-plugin-admin-addon-user-manager#7]
Filter

- [x] by groups
- [x] by access level

Search

- [x] by username
- [x] by full name
- [x] by email

**Comment by enzimage** [comment]
Hi David
I would add "access level" as well (So one can find everyone who has "site.login" or filter out anyone who is an admin)

**Comment by david-szabo97** [comment]
Implemented in v1.5.0
