### ISSUE TITLE
Call to a member function id() on null after upgrate Grav to version 1.6.24

### ISSUE THREAD

**Issue by Leandro-b-03** [david-szabo97/grav-plugin-admin-addon-user-manager#71]
Hello everyone,
After I've upgraded Grav to version 1.6.24 I start to receive this error when I trying to go to the plugin:

> /var/www/html/user/plugins/admin-addon-user-manager/admin-addon-user-manager.php

      }
     
      public function onAdminTwigTemplatePaths($e) {
        $paths = $e['paths'];
        $paths[] = __DIR__ . DS . 'templates';
        $e['paths'] = $paths;
      }
     
      public function onTwigSiteVariables() {
        $page = $this->grav['page'];
        $twig = $this->grav['twig'];
        $session = $this->grav['session'];
        $uri = $this->grav['uri'];
     
        foreach ($this->managers as $manager) {
          if ($page->slug() === $manager->getLocation() && $this->grav['admin']->authorize(['admin.super', $manager->getRequiredPermission()])) {
            $session->{$this->name . '.previous_url'} = $uri->route() . $uri->params();
     
            $page = $this->grav['admin']->page(true);
            $page->id('aaum-' . implode('/', $uri->paths()));
     
            $twig->twig_vars['context'] = $page;
     
            $vars = $manager->handleRequest();
            $twig->twig_vars = array_merge($twig->twig_vars, $vars);
     
            return true;
          }
        }
      }
     
      public function onAdminTaskExecute($e) {
        foreach ($this->managers as $manager) {
          if ($this->grav['admin']->authorize(['admin.super', $manager->getRequiredPermission()])) {
            $result = $manager->handleTask($e);
     
            if ($result) {
              return true;
            }
          }

Arguments

    "Call to a member function id() on null"

Here Environment & details:
GET Data empty
POST Data empty
Files empty
Cookies
grav-tabs-state | "{"tab-content.options.advanced":"data.advanced","tab-options.routes.registration.Security":"data.options","tab-content.options":"data.options"}"
-- | --
grav-site-40d1b2d-admin | "da80d9c6fa81849ded52e8e86a0eb8b6"
grav-site-40d1b2d | "334050bff2fac18d0fe886a27a46a4eb"

user | User {#163}
-- | --
messages | Message {#165}
expert | false
redirect_after_login | false
admin-addon-user-manager.previous_url | "/admin/user-manager"

REDIRECT_STATUS | "200"
-- | --
HTTP_HOST | "docs.printi.com.br"
HTTP_USER_AGENT | "Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0"
HTTP_ACCEPT | "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
HTTP_ACCEPT_LANGUAGE | "en-US,en;q=0.5"
HTTP_ACCEPT_ENCODING | "gzip, deflate"
HTTP_CONNECTION | "keep-alive"
HTTP_COOKIE | "grav-tabs-state={%22tab-content.options.advanced%22:%22data.advanced%22%2C%22tab-options.routes.registration.Security%22:%22data.options%22%2C%22tab-content.options%22:%22data.options%22}; grav-site-40d1b2d-admin=da80d9c6fa81849ded52e8e86a0eb8b6; grav-site-40d1b2d=334050bff2fac18d0fe886a27a46a4eb ◀"
HTTP_UPGRADE_INSECURE_REQUESTS | "1"
PATH | "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
SERVER_SIGNATURE | "<address>Apache/2.4.25 (Debian) Server at docs.printi.com.br Port 80</address>

APACHE_LOG_DIR | "/var/log/apache2"
-- | --
LANG | "C"
HOSTNAME | "b50638b48251"
APACHE_CONFDIR | "/etc/apache2"
APACHE_LOCK_DIR | "/var/lock/apache2"
PHPIZE_DEPS | "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c"
GPG_KEYS | "1729F83938DA44E27BA0F4D3DBDB397470D12172 B1B44D8F021E4E2D6021E995DC9FF8D3EE5AF27F"
PHP_EXTRA_CONFIGURE_ARGS | "--with-apxs2 --disable-cgi"
PHP_ASC_URL | "https://secure.php.net/get/php-7.2.13.tar.xz.asc/from/this/mirror"
PHP_CFLAGS | "-fstack-protector-strong -fpic -fpie -O2"
PHP_EXTRA_BUILD_DEPS | "apache2-dev"
PWD | "/var/www"
PHP_LDFLAGS | "-Wl,-O1 -Wl,--hash-style=both -pie"
APACHE_RUN_GROUP | "www-data"
APACHE_RUN_DIR | "/var/run/apache2"
PHP_INI_DIR | "/usr/local/etc/php"
PHP_URL | "https://secure.php.net/get/php-7.2.13.tar.xz/from/this/mirror"
APACHE_ENVVARS | "/etc/apache2/envvars"
PHP_CPPFLAGS | "-fstack-protector-strong -fpic -fpie -O2"
APACHE_RUN_USER | "www-data"
GRAV_VERSION | "1.5.5"
PHP_VERSION | "7.2.13"
APACHE_PID_FILE | "/var/run/apache2/apache2.pid"
SHLVL | "0"
GRAV_SHA1 | "af0433facdae1afeb1d973a66db2315c5022b10d"
PHP_MD5 | ""
PATH | "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PHP_SHA256 | "14b0429abdb46b65c843e5882c9a8c46b31dfbf279c747293b8ab950c2644a4b"

Registered Handlers
0. Whoops\Handler\PrettyPageHandler
1. Whoops\Handler\CallbackHandler

Thanks!

**Comment by david-szabo97** [comment]
Everything seems to work fine on v1.6.31. Please reopen if the issue still persists. Thanks!
