### ISSUE TITLE
Configure password requirements to allow passphrase

### ISSUE THREAD

**Issue by fnetX** [david-szabo97/grav-plugin-admin-addon-user-manager#74]
Hello,

I think that enforcing some requirements to passwords is a bad style in 2020 (also see https://theworld.com/~reinhold/diceware.html and https://xkcd.com/936/). 

I'd thus like to see a configuration option for password requirements to remove annoying limits like this plugin currently uses or even change the default behaviour to prefer passphrases.

Thank you very much.

**Comment by david-szabo97** [comment]
Grav v1.7.0 has a built-in interface for managing users and groups. 🎉 I'm discontinuing the plugin. Thanks for using my plugin for the time being! 🙇

**Comment by fnetX** [comment]
Thank you for your plugin and for providing a solution while there was no such option in Grav. :heart:
