### ISSUE TITLE
Enhancement: Event Hook onUserRemove

### ISSUE THREAD

**Issue by bkraegelin** [david-szabo97/grav-plugin-admin-addon-user-manager#76]
Please create an event hook when user gets removed.

Background:
When a new user registers (or gets created by admin) I allocate additional resources outside grav using my own plugin. When removing users I like to remove these ressources in in a comprehensible way.

Thanks,
Birger

**Comment by david-szabo97** [comment]
Hi @bkraegelin ! In the latest version (v2.4.0) you can now use:
* Event hook for user removal: `AAUM_onUserRemove` (`user` object passed)
* Event hook for group removal: `AAUM_OnGroupRemove` (`group` object passed)
