### ISSUE TITLE
Access login and group in admin page advanced tab missing

### ISSUE THREAD

**Issue by sherpadawan** [david-szabo97/grav-plugin-admin-addon-user-manager#79]
It would be nice to have access.site.login and access.groups in default page blueprint in order to give access or not to a page.

**Comment by david-szabo97** [comment]
I don't see any reason for this to be in this plugin. Seems totally unrelated. This plugin doesn't manage access permissions.

**Comment by sherpadawan** [comment]
True. Anyway this will disappear with next grav releases. Hope we'll have better user and access managements as core plugins.
