### ISSUE TITLE
2fa and Save user bugs

### ISSUE THREAD

**Issue by Andy-Flack** [david-szabo97/grav-plugin-admin-addon-user-manager#80]
Due to the link at the bottom of the plugin admin going to the general admin buglist there are 2 bugs on there relating to this module.
#1988 
ADMIn 2FA saving a user with 2fa enabled regenerates the 2fa code and locks out the user

#1992
attempting to save user calls with null

**Comment by david-szabo97** [comment]
Both issues you mentioned are unrelated to this plugin. They are already fixed in the Core and Login plugin.
