### ISSUE TITLE
Undefined index username

### ISSUE THREAD

**Issue by preraksola** [david-szabo97/grav-plugin-admin-addon-user-manager#81]
I have the latest version of Grav and the plugin installed.

While creating a new user, upon clicking "Save", I get a popup, saying unsaved changes, do you want to continue (which is quite weird). 

After clicking Continue, the user is not created and I get an error saying `Undefined indes username`.

If I disable the plugin, I can successfully create the new user.

**Comment by arkhi** [comment]
I have the latest versions of Grav and plugins installed as well, and a similar message: `Undefined index: username`

**Comment by sebasvisser** [comment]
I'm running into this problem as well... Is there a fix known yet?

**Comment by arkhi** [comment]
@sebasvisser: We don’t need this plugin with the latest versions of Grav admin plugin (since Grav 1.7, I think), as it is implemented in the admin plugin.

**Comment by sebasvisser** [comment]
@arkhi Aah superb! Thanks for your reply. I removed the plugin and the site is back up and running! Thanks for your help.

**Comment by david-szabo97** [comment]
Grav v1.7.0 has a built-in interface for managing users and groups. 🎉 I'm discontinuing the plugin. Thanks for using my plugin for the time being! 🙇
